language: python

sudo: required

before_install:
- curl https://fonts.google.com/download\?family\=Open%20Sans --output ~/opensans.zip
- curl https://www.freefontspro.com/d/14454/arial.zip --output ~/arial.zip
- sudo mkdir -p /usr/share/fonts/googlefonts && sudo unzip ~/opensans.zip -d /usr/share/fonts/googlefonts
- sudo mkdir -p /usr/share/fonts/googlefonts && sudo unzip ~/arial.zip -d /usr/share/fonts/googlefonts
- sudo chmod 755 /usr/share/fonts/googlefonts
- sudo chmod -R 644 /usr/share/fonts/googlefonts/*
- sudo fc-cache -fv

# install lot of fonts
addons:
  apt:
    packages:
      - fonts-ipafont-gothic
      - fonts-wqy-zenhei
      - fonts-thai-tlwg
      - fonts-kacst
      - ttf-freefont
      - msttcorefonts
      - ttf-mscorefonts-installer

python:
- 3.6
install: pip install -U tox-travis
script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dvarotto
  password:
    secure: M8Unj3nu+aiK2akl3MxT8GYXK7b3bu5MqZ6Mr9rfLnWJ5rYTHgEUJZFWHCw+NHKpVnC17w/GUvATfO8LfQ3DviNufh6e6l2vXQTn5+P/7pllXxBGosipIScZMD86Md2ISKKcvVguSpwe9x3Q31Dgy8W3Zwi3A6wUsFD7r+DNorAmDOPRyFjWqRU1iAIDBBtORoF8YhzcZTu9LDZVai8AtTy8tq6K48q03aieDV853IowU6Yf395i03L1eRaVGN0RRkUH35ZBV8v6DI5fjcqmc8vzr0v2ODrCEhgAfcVXycAqhroaUXPKMCBg7pgWhXOV6NhJx2DzxMk3qXb94/wnF9atbP2mlY/6cHmeowDx/XbumOuvmbdoENhTf4w0ZrYejHEh7yQqyZuGoSeeeCD1bM+kGwyTm8APbGq/0yu18Q8GJt6MP/xbfGTI8yg0pEgEc71cHJ9/IilDltmca0GFusbAE+3+a6yvE3qin/Fokhbadu9qISNdBQcpOI3Ooa46nYUr8JIprr7MIZ9rxspq/ruEGsrKgnWMjzpOCchRfnPDci5HT2JdIrxnTXoznysp2OZtPDXb6TxNXRYiBoVuIXScH9lwPoJjR93yWSArH1ljV+1GNWGQ6U/n0UWgE9bC8ubG81G/rtbkE+iZtEc8yOEObYNg3cS16oWJWmPC+Bw=
  on:
    tags: true
    repo: dariosky/visualdiff
    python: 3.6
